//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_BIProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConnectionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConnectionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCF_BIProject.ConnectionStrings", typeof(ConnectionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=192.168.1.10;database=fabrication;uid=axel;password=axel;.
        /// </summary>
        internal static string ISqlData_0CString {
            get {
                return ResourceManager.GetString("ISqlData_0CString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=192.168.1.11;database=preparation;uid=axel;password=axel;.
        /// </summary>
        internal static string ISqlData_1CString {
            get {
                return ResourceManager.GetString("ISqlData_1CString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=192.168.1.12;database=expedition;uid=axel;password=axel;.
        /// </summary>
        internal static string ISqlData_2CString {
            get {
                return ResourceManager.GetString("ISqlData_2CString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonApplication.
        /// </summary>
        internal static string ISqlDatabases {
            get {
                return ResourceManager.GetString("ISqlDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string MaxConnecftions {
            get {
                return ResourceManager.GetString("MaxConnecftions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OSqlAuth_0 {
            get {
                return ResourceManager.GetString("OSqlAuth_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://localhost:27017.
        /// </summary>
        internal static string OSqlData_0 {
            get {
                return ResourceManager.GetString("OSqlData_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://192.168.1.3:27017.
        /// </summary>
        internal static string OSqlData_1 {
            get {
                return ResourceManager.GetString("OSqlData_1", resourceCulture);
            }
        }
    }
}
